#!/usr/bin/env bash
# DO NOT EDIT — this file is generated from cm.yaml and will be overwritten.
# To make changes, edit cm.yaml and run: cm update
# Generated by container-magic: https://github.com/markhedleyjones/container-magic

set -euo pipefail

# Configuration
IMAGE_NAME="markhedleyjones-github-io"
WORKSPACE_NAME="docs"
USER_NAME="user"
USER_UID="1000"
USER_GID="1000"
WORKDIR="/home/user"
TARGET="production"
TAG="latest"

# Detect runtime backend
if command -v docker >/dev/null 2>&1; then
	RUNTIME="docker"
elif command -v podman >/dev/null 2>&1; then
	RUNTIME="podman"
else
	echo "Error: Neither docker nor podman found in PATH" >&2
	exit 1
fi

# Parse arguments
while [[ $# -gt 0 ]]; do
	case "$1" in
	--uid)
		USER_UID="$2"
		shift 2
		;;
	--gid)
		USER_GID="$2"
		shift 2
		;;
	--tag)
		TAG="$2"
		shift 2
		;;
	--help | -h)
		echo "Usage: $0 [options]"
		echo ""
		echo "Build a Docker image for the production target stage."
		echo ""
		echo "Options:"
		echo "  --tag TAG     Override image tag (default: latest)"
		echo "  --uid UID     Override user UID (default: $USER_UID)"
		echo "  --gid GID     Override user GID (default: $USER_GID)"
		exit 0
		;;
	*)
		echo "Error: Unknown argument '$1'" >&2
		echo "Use '$0 --help' for more information" >&2
		exit 1
		;;
	esac
done

echo "Building image: ${IMAGE_NAME}:${TAG} (target: ${TARGET})"
${RUNTIME} build \
	--target "${TARGET}" \
	--build-arg USER_NAME="${USER_NAME}" \
	--build-arg USER_UID="${USER_UID}" \
	--build-arg USER_GID="${USER_GID}" \
	--build-arg WORKSPACE_NAME="${WORKSPACE_NAME}" \
	--tag "${IMAGE_NAME}:${TAG}" \
	.

echo "Image built successfully: ${IMAGE_NAME}:${TAG}"
echo "Workspace included in image at: ${WORKDIR}/${WORKSPACE_NAME}"
echo ""
echo "To run the image, use: ./run.sh [command]"
