#!/usr/bin/env bash
# Standalone build script
# Generated by container-magic: https://github.com/markhedleyjones/container-magic
# Can be run without container-magic installed

set -euo pipefail

# Configuration
IMAGE_NAME="markhedleyjones-github-io"
WORKSPACE_NAME="docs"
USER_NAME="user"
USER_UID="1000"
USER_GID="1000"
WORKDIR="/home/user"
DEFAULT_TARGET="production"
AVAILABLE_TARGETS=("base" "development" "production")

# Detect runtime backend
if command -v podman >/dev/null 2>&1; then
	RUNTIME="podman"
elif command -v docker >/dev/null 2>&1; then
	RUNTIME="docker"
else
	echo "Error: Neither docker nor podman found in PATH" >&2
	exit 1
fi

# Parse arguments
TARGET="${1:-$DEFAULT_TARGET}"

# Determine tag based on target
if [[ "$TARGET" == "production" ]]; then
	TAG="latest"
else
	TAG="$TARGET"
fi

# Show help if requested
if [[ "$TARGET" == "--help" || "$TARGET" == "-h" ]]; then
	echo "Usage: $0 [target]"
	echo ""
	echo "Build a Docker image for the specified target stage."
	echo ""
	echo "Arguments:"
	echo "  target    Build target (default: $DEFAULT_TARGET)"
	echo ""
	echo "Available targets:"
	for t in "${AVAILABLE_TARGETS[@]}"; do
		if [[ "$t" == "$DEFAULT_TARGET" ]]; then
			echo "  $t (default)"
		else
			echo "  $t"
		fi
	done
	exit 0
fi

# Validate target
valid_target=false
for t in "${AVAILABLE_TARGETS[@]}"; do
	if [[ "$t" == "$TARGET" ]]; then
		valid_target=true
		break
	fi
done

if [[ "$valid_target" == "false" ]]; then
	echo "Error: Invalid target '$TARGET'" >&2
	echo "Available targets: ${AVAILABLE_TARGETS[*]}" >&2
	echo "Use '$0 --help' for more information" >&2
	exit 1
fi

echo "Building image: ${IMAGE_NAME}:${TAG} (target: ${TARGET})"

${RUNTIME} build \
	--target "${TARGET}" \
	--build-arg USER_NAME="${USER_NAME}" \
	--build-arg USER_UID="${USER_UID}" \
	--build-arg USER_GID="${USER_GID}" \
	--build-arg WORKDIR="${WORKDIR}" \
	--build-arg WORKSPACE_NAME="${WORKSPACE_NAME}" \
	--tag "${IMAGE_NAME}:${TAG}" \
	.

echo "Image built successfully: ${IMAGE_NAME}:${TAG}"
echo "Workspace included in image at: ${WORKDIR}/${WORKSPACE_NAME}"
echo ""
echo "To run the image, use: ./run.sh [command]"
