# DO NOT EDIT — this file is generated from cm.yaml and will be overwritten.
# To make changes, edit cm.yaml and run: cm update
# Generated by container-magic: https://github.com/markhedleyjones/container-magic

################################################################################
# Stage: base
################################################################################
FROM debian:bookworm-slim AS base

ARG USER_GID=1000 \
    USER_UID=1000 \
    USER_NAME=user \
    USER_HOME=/home/user \
    WORKSPACE_NAME=docs
ENV WORKSPACE=${USER_HOME}/${WORKSPACE_NAME}
WORKDIR ${USER_HOME}
ENV GEM_HOME="${USER_HOME}/gems" \
    PATH="${USER_HOME}/gems/bin:$PATH"
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        ruby-full \
        zlib1g-dev && \
    rm -rf /var/lib/apt/lists/*
# Create user account (handles renaming if UID exists with different name)
# hadolint ignore=DL4006
RUN if [ "${USER_NAME}" != "root" ]; then \
        EXISTING_USER=$(getent passwd "${USER_UID}" | cut -d: -f1); \
        if [ "${EXISTING_USER}" = "${USER_NAME}" ]; then \
            echo "User ${USER_NAME} with UID ${USER_UID} already exists, skipping creation"; \
        elif [ -n "${EXISTING_USER}" ]; then \
            echo "Renaming user ${EXISTING_USER} to ${USER_NAME}"; \
            usermod -l "${USER_NAME}" "${EXISTING_USER}" && \
            usermod -d "${USER_HOME}" -m "${USER_NAME}" || true; \
        else \
            getent group "${USER_GID}" >/dev/null 2>&1 || \
                groupadd --gid "${USER_GID}" "${USER_NAME}"; \
            useradd --uid "${USER_UID}" --gid "${USER_GID}" --home-dir "${USER_HOME}" --create-home "${USER_NAME}"; \
        fi && \
        chown "${USER_UID}:${USER_GID}" "${USER_HOME}"; \
    fi
USER ${USER_NAME}
RUN gem install jekyll bundler
COPY --chown=${USER_NAME}:${USER_NAME} docs/Gemfile docs/Gemfile.lock /tmp/
RUN cd /tmp && bundle install

################################################################################
# Stage: development
################################################################################
FROM base AS development

ARG USER_GID=1000 \
    USER_UID=1000 \
    USER_NAME=user \
    USER_HOME=/home/user
USER ${USER_NAME}

################################################################################
# Stage: production
################################################################################
FROM base AS production

ARG USER_GID=1000 \
    USER_UID=1000 \
    USER_NAME=user \
    USER_HOME=/home/user
COPY --chown=${USER_NAME}:${USER_NAME} docs ${WORKSPACE}
USER ${USER_NAME}
