# Dockerfile
# Generated by container-magic: https://github.com/markhedleyjones/container-magic
# Source config: cm.yaml or container-magic.yaml
# Install: pip install container-magic
# Update: cm update

################################################################################
# Stage: base
################################################################################
FROM debian:bullseye-slim AS base

# User configuration
ARG USER_GID=1000 \
    USER_UID=1000 \
    USER_NAME=user \
    USER_HOME=/home/user

# Setup workspace (only in base stage, inherited by others)
ARG WORKSPACE_NAME=docs
ARG USER_HOME=/home/user
ENV WORKDIR=${USER_HOME}
ENV WORKSPACE=${USER_HOME}/${WORKSPACE_NAME}
WORKDIR ${USER_HOME}

# Environment variables
ENV GEM_HOME=${WORKDIR}/gems
ENV PATH=${WORKDIR}/gems/bin:$PATH
# Install system packages
RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
        build-essential \
        ruby-full \
        zlib1g-dev && \
    rm -rf /var/lib/apt/lists/*
# Create user account (handles renaming if UID exists with different name)
RUN if [ "${USER_NAME}" != "root" ]; then \
        # Check if the user already exists with exact match (name + uid + gid)
        if getent passwd "${USER_UID}" | grep -q "^${USER_NAME}:"; then \
            echo "User ${USER_NAME} with UID ${USER_UID} already exists, skipping creation"; \
        else \
            # Check if UID exists with a different name
            EXISTING_USER=$(getent passwd "${USER_UID}" | cut -d: -f1 || echo ""); \
            if [ -n "${EXISTING_USER}" ] && [ "${EXISTING_USER}" != "${USER_NAME}" ]; then \
                # Rename the existing user to our desired name
                echo "Renaming user ${EXISTING_USER} to ${USER_NAME}"; \
                usermod -l ${USER_NAME} ${EXISTING_USER} && \
                usermod -d ${USER_HOME} -m ${USER_NAME} || true; \
            else \
                # Create new user
                if ! getent group ${USER_GID} >/dev/null 2>&1; then \
                    groupadd --gid ${USER_GID} ${USER_NAME}; \
                fi && \
                useradd --uid ${USER_UID} --gid ${USER_GID} --home-dir ${USER_HOME} --create-home ${USER_NAME}; \
            fi \
        fi && \
        # Ensure home directory ownership (may have been created by WORKDIR)
        chown ${USER_UID}:${USER_GID} ${USER_HOME}; \
    fi
# Switch to user
USER ${USER_NAME}
RUN gem install jekyll bundler
COPY docs/Gemfile docs/Gemfile.lock /tmp/
RUN cd /tmp && bundle install

################################################################################
# Stage: development
################################################################################
FROM base AS development

# User configuration
ARG USER_GID=1000 \
    USER_UID=1000 \
    USER_NAME=user \
    USER_HOME=/home/user

################################################################################
# Stage: production
################################################################################
FROM base AS production

# User configuration
ARG USER_GID=1000 \
    USER_UID=1000 \
    USER_NAME=user \
    USER_HOME=/home/user
# Copy workspace into image
COPY --chown=${USER_UID}:${USER_GID} docs ${WORKSPACE}
