#!/usr/bin/env python3
"""Generate narrow variants of content images and record every image's size.

Content images are referenced through _includes/image.html, which needs to know
each image's intrinsic size to reserve layout space, and which candidates exist
so the browser can pick one. Both come from _data/image_sizes.yml, written here.

Run from the repository root after adding or replacing an image:

    ./generate_responsive_images.py
"""

import re
import sys
from pathlib import Path

from PIL import Image

DOCS = Path(__file__).parent / "docs"
SIZES_DATA = DOCS / "_data" / "image_sizes.yml"

# Content sits in a 1000px column, so the widest an image is ever drawn is
# ~940 CSS px. A 1600px source covers that at 1.7x; 800px covers the
# half-width slots, and 400px covers a phone without sending it a desktop file.
VARIANT_WIDTHS = (400, 800)
WEBP_QUALITY = 82

# Below this there is nothing worth splitting - the source is already small.
MIN_WIDTH_TO_SPLIT = 900
VARIANT_PATTERN = re.compile(r"-\d+w$")

SOURCE_GLOBS = ("_posts/*", "*.html", "*.md")
IMG_TAG_SRC = re.compile(r'<img[^>]*\ssrc="(/media/[^"]+)"')
MARKDOWN_IMG = re.compile(r"!\[[^\]]*\]\((/media/[^)\s]+)\)")
INCLUDE_IMG = re.compile(r'{%-?\s*include\s+image\.html[^%]*\ssrc="(/media/[^"]+)"')


def referenced_images():
    """Every /media path the site's content points at, in sorted order."""
    found = set()
    for pattern in SOURCE_GLOBS:
        for path in DOCS.glob(pattern):
            if not path.is_file():
                continue
            text = path.read_text(encoding="utf-8", errors="replace")
            for regex in (IMG_TAG_SRC, MARKDOWN_IMG, INCLUDE_IMG):
                found.update(regex.findall(text))
    return sorted(found)


def variant_path(path, width):
    return path.with_name(f"{path.stem}-{width}w{path.suffix}")


def main():
    entries = {}
    generated = 0
    missing = []

    for url in referenced_images():
        path = DOCS / url.lstrip("/")
        if not path.exists():
            missing.append(url)
            continue

        # Skip variants themselves so reruns stay idempotent.
        if VARIANT_PATTERN.search(path.stem):
            continue

        if path.suffix.lower() == ".svg":
            # Vector: no raster variants, and the box is set by CSS.
            continue

        with Image.open(path) as image:
            width, height = image.size
            entry = {"width": width, "height": height, "variants": []}

            # Resizing an animated WebP through Pillow keeps only the first
            # frame, so leave those alone and serve the original.
            animated = getattr(image, "n_frames", 1) > 1

            if (
                path.suffix.lower() == ".webp"
                and width >= MIN_WIDTH_TO_SPLIT
                and not animated
            ):
                for target_width in VARIANT_WIDTHS:
                    target = variant_path(path, target_width)
                    if not target.exists():
                        scaled = image.copy()
                        scaled.thumbnail((target_width, 10**6), Image.LANCZOS)
                        scaled.save(target, "WEBP", quality=WEBP_QUALITY, method=6)
                        generated += 1
                    with Image.open(target) as small:
                        entry["variants"].append(small.size[0])

        entries[url] = entry

    lines = [
        "# Generated by generate_responsive_images.py - do not edit by hand.",
        "# Intrinsic size of every content image, and the widths of any narrower",
        "# variants sitting beside it. _includes/image.html builds the srcset from",
        "# these - storing the widths rather than the URLs keeps the lines short",
        "# enough that the repository's YAML formatter leaves them alone.",
        "",
    ]
    for url, entry in sorted(entries.items()):
        lines.append(f'"{url}":')
        lines.append(f"  width: {entry['width']}")
        lines.append(f"  height: {entry['height']}")
        if entry["variants"]:
            lines.append("  variants:")
            lines.extend(f"    - {width}" for width in entry["variants"])
    SIZES_DATA.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"indexed {len(entries)} images, generated {generated} new variants")
    print(f"wrote {SIZES_DATA.relative_to(Path(__file__).parent)}")
    if missing:
        print(f"\n{len(missing)} referenced images are missing:", file=sys.stderr)
        for url in missing:
            print(f"  {url}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
