#!/usr/bin/env bash
# Standalone production run script
# Generated by container-magic: https://github.com/markhedleyjones/container-magic
# Can be run without container-magic installed

set -euo pipefail

IMAGE_NAME="markhedleyjones-github-io"
TAG="latest"
WORKDIR="/home/user"
WORKSPACE_NAME="docs"
SHELL="bash"

# Detect runtime backend
if command -v podman >/dev/null 2>&1; then
	RUNTIME="podman"
elif command -v docker >/dev/null 2>&1; then
	RUNTIME="docker"
else
	echo "Error: Neither podman nor docker found in PATH"
	exit 1
fi

# Check if image exists locally to avoid registry prompts
if ! ${RUNTIME} image inspect "${IMAGE_NAME}:${TAG}" &>/dev/null; then
	echo "Error: Image ${IMAGE_NAME}:${TAG} not found locally"
	echo "Build it with: ./build.sh"
	exit 1
fi

# Build base run arguments (common to all commands)
BASE_RUN_ARGS=("--rm")
BASE_RUN_ARGS+=("--hostname" "${IMAGE_NAME}")

# Custom command handlers

run_serve() {
	# Start Jekyll dev server with live reload
	local RUN_ARGS=("${BASE_RUN_ARGS[@]}")
	# Port publishing
	RUN_ARGS+=("--publish" "4111:4111")
	RUN_ARGS+=("--publish" "4112:4112")

	${RUNTIME} run "${RUN_ARGS[@]}" \
		-w "${WORKDIR}" \
		"${IMAGE_NAME}:${TAG}" \
		"${SHELL}" -c "cd \${WORKSPACE} && bundle exec jekyll serve --host 0.0.0.0 --port 4111 --livereload --livereload-port 4112"
}

# Check for custom command
if [ $# -gt 0 ]; then
	case "$1" in
	serve)
		shift
		run_serve "$@"
		exit $?
		;;
	esac
fi

# Use base run arguments
RUN_ARGS=("${BASE_RUN_ARGS[@]}")

# Run command or shell
if [ $# -gt 0 ]; then
	# Run specific command (no TTY flags)
	${RUNTIME} run "${RUN_ARGS[@]}" \
		-w "${WORKDIR}/${WORKSPACE_NAME}" \
		"${IMAGE_NAME}:${TAG}" \
		"${SHELL}" -c "$*"
else
	# Interactive shell (add TTY flags only if stdin is a TTY)
	if [[ -t 0 ]]; then
		RUN_ARGS+=("--interactive" "--tty")
	fi
	${RUNTIME} run "${RUN_ARGS[@]}" \
		-w "${WORKDIR}/${WORKSPACE_NAME}" \
		"${IMAGE_NAME}:${TAG}" \
		"${SHELL}"
fi
